runtime: python27
api_version: 1
threadsafe: true

# Third party libraries loaded from the App Engine environment.
libraries:
- name: jinja2
  version: "2.6"

handlers:

- url: /bower_components
  static_dir: frontend/build/es5-bundled/bower_components
  secure: always

- url: /images
  static_dir: frontend/build/es5-bundled/images
  secure: always

- url: /src
  static_dir: frontend/build/es5-bundled/src
  secure: always

- url: /manifest.json
  static_files: frontend/build/es5-bundled/manifest.json
  upload: frontend/build/es5-bundled/manifest.json
  secure: always
  
- url: /caminata
  script: main.app  
  login: required
  secure: always
  
- url: /
  script: main.app  
  login: required
  secure: always
  
- url: /.*
  static_files: frontend/build/es5-bundled/index.html
  upload: frontend/build/es5-bundled/index.html
  secure: always
  application_readable: true
